import express from "express";
import cors from "cors";
import "dotenv/config";
import cookieParser from "cookie-parser";
import connectdb from "./config/mongodb.js";
import authRouter from "./routes/authRoute.js";
import userRouter from "./routes/userRountes.js";
const app = express();
const port = process.env.PORT || 4000;
connectdb();
app.use(express.json());
app.use(cookieParser());
const allowedOrigins = ["https://authentication-system-xbhc.onrender.com"];
app.use(cors({ origin: allowedOrigins, credentials: true }));
app.get("/", (req, res) => {
  res.send("API working");
});
app.use("/api/auth", authRouter);
app.use("/api/user", userRouter);
app.listen(port, () => console.log(`Server started on Port ${port}`));
